### ISSUE TITLE
Replay parser loopback error

### ISSUE THREAD

**Issue by Beherith** [gajop/spring-launcher#83]
One specific replay (which plays fine when launched from spring.exe) does not show up in chobby. I looked at launcher logs, and it seems that parsing of it is failing, but the spring-launcher log does not specify which replay failed to parse:

[2021-03-30 13:32:54.598] [error] UnhandledRejection Error: Error: unexpected end of file
    at Gunzip.cb (C:\Users\psarkozy\AppData\Local\Programs\Beyond-All-Reason\resources\app.asar\node_modules\node-gzip\dist\index.js:17:49)
    at Gunzip.zlibBufferOnError (zlib.js:129:8)
    at Gunzip.emit (events.js:315:20)
    at Zlib.zlibOnError [as onerror] (zlib.js:183:8)
[2021-03-30 13:32:57.397] [error] UnhandledRejection TypeError: Cannot read property 'playerNum' of undefined
    at DemoParser.parsePackets (C:\Users\psarkozy\AppData\Local\Programs\Beyond-All-Reason\resources\app.asar\node_modules\sdfz-demo-parser\dist\demo-parser.js:185:33)
    at DemoParser.parseDemo (C:\Users\psarkozy\AppData\Local\Programs\Beyond-All-Reason\resources\app.asar\node_modules\sdfz-demo-parser\dist\demo-parser.js:39:29)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Bridge.<anonymous> (C:\Users\psarkozy\AppData\Local\Programs\Beyond-All-Reason\resources\app.asar\src\exts\replay_handler.js:15:15)
[2021-03-30 13:32:57.414] [error] UnhandledRejection TypeError: Cannot read property 'playerNum' of undefined
    at DemoParser.parsePackets (C:\Users\psarkozy\AppData\Local\Programs\Beyond-All-Reason\resources\app.asar\node_modules\sdfz-demo-parser\dist\demo-parser.js:185:33)
    at DemoParser.parseDemo (C:\Users\psarkozy\AppData\Local\Programs\Beyond-All-Reason\resources\app.asar\node_modules\sdfz-demo-parser\dist\demo-parser.js:39:29)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Bridge.<anonymous> (C:\Users\psarkozy\AppData\Local\Programs\Beyond-All-Reason\resources\app.asar\src\exts\replay_handler.js:15:15)
[20210320_002757_Comet_Catcher_Remake_1_104.0.1-1828-g1f481b7_BAR.sdfz.zip](https://github.com/gajop/spring-launcher/files/6228666/20210320_002757_Comet_Catcher_Remake_1_104.0.1-1828-g1f481b7_BAR.sdfz.zip)

**Comment by gajop** [comment]
@Jazcash

**Comment by Jazcash** [comment]
Is this a single player replay? Works for me on latest version so I'm guessing you're on an older version of sdfz-demo-parser

**Comment by gajop** [comment]
I've bumped the replay handler. Hopefully it fixes this
PS: (didn't mean to close yet, should be tested first)
